databases:
  - name: praktix-db
    plan: free
    databaseName: praktix
    user: praktix

services:
  - type: web
    name: praktix
    runtime: docker
    plan: free
    repo: https://github.com/daviddornyoh9-spec/laravel
    branch: main
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: Praktix
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: praktix-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: praktix-db
          property: connectionString
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
